# site settings
title: 
subtitle: Jackson Choral Society
email: info@jacksonchoralsociety.com
description: The Voice of the People, for a Better World through Music
baseurl: "" # the subpath of your site, e.g. /blog
url: https://trusting-lalande-d1706a.netlify.app/
street_address: 319 Vann Dr. &#35E264
city: Jackson
state: TN
zip_code: 38305
country: United States of America
#phone: (716) 555-5555
donation_link: "https://donate.everydayhero.com/us/jackson-choral-society/jackson-choral-society/"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown
# Jekyll: Toggle Auto Build

sass:
  style: compressed
